{% set name = "duc" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zevv/duc/releases/download/{{ version }}/duc-{{ version }}.tar.gz
  sha256: f84d39abf5afaade26cfa81382add6e97fb3b07fc626c2a6260e8d60c89c5a78

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - make
    - pkg-config
  host:
    - tokyocabinet
    - ncurses
    - cairo
    - glib
    - pango
    - xorg-libx11
  run:
    - pango
    - xorg-libx11
    - tokyocabinet

test:
  commands:
    - duc --help
    - duc index -d duc.db .
    - duc ls -d duc.db .
    - duc graph -d duc.db .

about:
  home: http://duc.zevv.nl/
  # TODO: On next release will be released under LGPL-3.0-only
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Duc is a collection of tools for inspecting and visualizing disk usage.
  description: |
    Duc is a collection of tools for indexing, inspecting and visualizing disk usage. 
    Duc maintains a database of accumulated sizes of directories of the file system, 
    and allows you to query this database with some tools, or create fancy graphs 
    showing you where your bytes are. 
  doc_url: https://rawgit.com/zevv/duc/master/doc/duc.1.html
  dev_url: https://github.com/zevv/duc

extra:
  recipe-maintainers:
    - rhpvorderman
