{% set name = "duc" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zevv/duc/releases/download/{{ version }}/duc-{{ version }}.tar.gz
  sha256: c69512ca85b443e42ffbb4026eedd5492307af612047afb9c469df923b468bfd

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - make
    - pkg-config
  host:
    - tokyocabinet
    - ncurses
    - cairo
    - glib
    - pango
    - xorg-libx11
  run:
    - pango
    - xorg-libx11
    - tokyocabinet

test:
  commands:
    - duc --help
    - duc index -d duc.db .
    - duc ls -d duc.db .
    - duc graph -d duc.db .

about:
  home: http://duc.zevv.nl/
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Duc is a collection of tools for inspecting and visualizing disk usage.
  description: |
    Duc is a collection of tools for indexing, inspecting and visualizing disk usage. 
    Duc maintains a database of accumulated sizes of directories of the file system, 
    and allows you to query this database with some tools, or create fancy graphs 
    showing you where your bytes are. 
  doc_url: https://rawgit.com/zevv/duc/master/doc/duc.1.html
  dev_url: https://github.com/zevv/duc

extra:
  recipe-maintainers:
    - rhpvorderman
